/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.enums;


import it.ripapp.ripapp.jooqgen.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Demisematchtype implements EnumType {

    contact("contact"),

    relative("relative"),

    city("city");

    private final String literal;

    private Demisematchtype(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "demisematchtype";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
