/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.enums;


import it.ripapp.ripapp.jooqgen.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Serverstatus implements EnumType {

    active("active"),

    under_maintenance("under_maintenance");

    private final String literal;

    private Serverstatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "serverstatus";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
