/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen;


import it.ripapp.ripapp.jooqgen.tables.Account;
import it.ripapp.ripapp.jooqgen.tables.AccountCity;
import it.ripapp.ripapp.jooqgen.tables.AccountInstanceid;
import it.ripapp.ripapp.jooqgen.tables.Agency;
import it.ripapp.ripapp.jooqgen.tables.AgencyDemise;
import it.ripapp.ripapp.jooqgen.tables.AgencyOperator;
import it.ripapp.ripapp.jooqgen.tables.Appversions;
import it.ripapp.ripapp.jooqgen.tables.City;
import it.ripapp.ripapp.jooqgen.tables.CounterSet;
import it.ripapp.ripapp.jooqgen.tables.Country;
import it.ripapp.ripapp.jooqgen.tables.Demise;
import it.ripapp.ripapp.jooqgen.tables.DemiseCity;
import it.ripapp.ripapp.jooqgen.tables.DemiseMatch;
import it.ripapp.ripapp.jooqgen.tables.DemiseRead;
import it.ripapp.ripapp.jooqgen.tables.DemiseRelative;
import it.ripapp.ripapp.jooqgen.tables.EndpointLogging;
import it.ripapp.ripapp.jooqgen.tables.KinshipText;
import it.ripapp.ripapp.jooqgen.tables.NotificationKinshipText;
import it.ripapp.ripapp.jooqgen.tables.NotificationText;
import it.ripapp.ripapp.jooqgen.tables.Phonebook;
import it.ripapp.ripapp.jooqgen.tables.Serverinfo;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.account_city</code>.
     */
    public static final AccountCity ACCOUNT_CITY = AccountCity.ACCOUNT_CITY;

    /**
     * The table <code>public.account_instanceid</code>.
     */
    public static final AccountInstanceid ACCOUNT_INSTANCEID = AccountInstanceid.ACCOUNT_INSTANCEID;

    /**
     * The table <code>public.agency</code>.
     */
    public static final Agency AGENCY = Agency.AGENCY;

    /**
     * The table <code>public.agency_demise</code>.
     */
    public static final AgencyDemise AGENCY_DEMISE = AgencyDemise.AGENCY_DEMISE;

    /**
     * The table <code>public.agency_operator</code>.
     */
    public static final AgencyOperator AGENCY_OPERATOR = AgencyOperator.AGENCY_OPERATOR;

    /**
     * The table <code>public.appversions</code>.
     */
    public static final Appversions APPVERSIONS = Appversions.APPVERSIONS;

    /**
     * The table <code>public.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>public.counter_set</code>.
     */
    public static final CounterSet COUNTER_SET = CounterSet.COUNTER_SET;

    /**
     * The table <code>public.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.demise</code>.
     */
    public static final Demise DEMISE = Demise.DEMISE;

    /**
     * The table <code>public.demise_city</code>.
     */
    public static final DemiseCity DEMISE_CITY = DemiseCity.DEMISE_CITY;

    /**
     * The table <code>public.demise_match</code>.
     */
    public static final DemiseMatch DEMISE_MATCH = DemiseMatch.DEMISE_MATCH;

    /**
     * The table <code>public.demise_read</code>.
     */
    public static final DemiseRead DEMISE_READ = DemiseRead.DEMISE_READ;

    /**
     * The table <code>public.demise_relative</code>.
     */
    public static final DemiseRelative DEMISE_RELATIVE = DemiseRelative.DEMISE_RELATIVE;

    /**
     * The table <code>public.endpoint_logging</code>.
     */
    public static final EndpointLogging ENDPOINT_LOGGING = EndpointLogging.ENDPOINT_LOGGING;

    /**
     * The table <code>public.kinship_text</code>.
     */
    public static final KinshipText KINSHIP_TEXT = KinshipText.KINSHIP_TEXT;

    /**
     * The table <code>public.notification_kinship_text</code>.
     */
    public static final NotificationKinshipText NOTIFICATION_KINSHIP_TEXT = NotificationKinshipText.NOTIFICATION_KINSHIP_TEXT;

    /**
     * The table <code>public.notification_text</code>.
     */
    public static final NotificationText NOTIFICATION_TEXT = NotificationText.NOTIFICATION_TEXT;

    /**
     * The table <code>public.phonebook</code>.
     */
    public static final Phonebook PHONEBOOK = Phonebook.PHONEBOOK;

    /**
     * The table <code>public.serverinfo</code>.
     */
    public static final Serverinfo SERVERINFO = Serverinfo.SERVERINFO;
}
