/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.bll;



import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Kinship implements EnumType {

    figlio("figlio"),
    figlia("figlia"),
    nipote_m("nipote_m"),
    zio("zio"),
    zia("zia"),
    padre("padre"),
    madre("madre"),
    moglie("moglie"),
    fratello("fratello"),
    sorella("sorella"),
    nonna("nonna"),
    nonno("nonno"),
    marito("marito"),
    matrigna("matrigna"),
    patrigno("patrigno"),
    figliastro("figliastro"),
    figliastra("figliastra"),
    fratellastro("fratellastro"),
    sorellastra("sorellastra"),
    cugino("cugino"),
    cugina("cugina"),
    pronipote_m("pronipote"),
    pronipote_f("pronipote_f"),
    nipote_f("nipote_f");

    private final String literal;

    private Kinship(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }


    @Override
    public String getName() {
        return "kinship";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
