/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.bll;


import org.jooq.Catalog;
import org.jooq.EnumType;



public enum Lang implements EnumType {

    it_("it"),

    en("en");

    private final String literal;

    private Lang(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }


    @Override
    public String getName() {
        return "lang";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
