/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.entityUpdate;

import it.ripapp.ripapp.bll.Kinship;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;


/*
* VINCOLI NON AGGIUNTI:
* unique(relativeid, accountid)
* unique(relativeid, phone)
* */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class DemiseRelative {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long relativeid;

    /*@ManyToOne(ma)
    @Cascade(CascadeType.ALL)
    private DemiseEntity demise;*/

    @OneToOne
    private AccountEntity account;

    private UUID demiseid;
    //private UUID accountid;
    private Kinship kinship;

    private String name;
    private String surname;
    private String email;
    private String phone; //? verificare utilizzo di demiserelative.phone in altre classi
    private String phonehash;
    private String prefix;


}
