/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.entityUpdate;
import it.ripapp.ripapp.bll.Kinship;
import it.ripapp.ripapp.bll.Lang;
import it.ripapp.ripapp.entityUpdate.compositeKeys.NotificationKinshipTextKey;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@IdClass(NotificationKinshipTextKey.class)
public class NotificationKinshipText {
    @Id
    private Kinship KINSHIP;
    @Id
    private Lang LANG;
    private String TEXT;
}
