/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.entityUpdate;




import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.UUID;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Telegram {

    @Id
    private UUID TELEGRAMID;

    private String NAME;
    private String SURNAME;
    private String EMAIL;
    private String RECEIVER;
    private String DEFUNCT;
    private String MESSAGE;

    private UUID USERID;
    private UUID DEMISEID;
    private Boolean APPROVEDPAY;
    private String PAYMENTID;
}
