/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.tables.AccountInstanceid;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountInstanceidRecord extends UpdatableRecordImpl<AccountInstanceidRecord> implements Record2<UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account_instanceid.accountid</code>.
     */
    public void setAccountid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account_instanceid.accountid</code>.
     */
    public UUID getAccountid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.account_instanceid.instanceid</code>.
     */
    public void setInstanceid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account_instanceid.instanceid</code>.
     */
    public String getInstanceid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AccountInstanceid.ACCOUNT_INSTANCEID.ACCOUNTID;
    }

    @Override
    public Field<String> field2() {
        return AccountInstanceid.ACCOUNT_INSTANCEID.INSTANCEID;
    }

    @Override
    public UUID component1() {
        return getAccountid();
    }

    @Override
    public String component2() {
        return getInstanceid();
    }

    @Override
    public UUID value1() {
        return getAccountid();
    }

    @Override
    public String value2() {
        return getInstanceid();
    }

    @Override
    public AccountInstanceidRecord value1(UUID value) {
        setAccountid(value);
        return this;
    }

    @Override
    public AccountInstanceidRecord value2(String value) {
        setInstanceid(value);
        return this;
    }

    @Override
    public AccountInstanceidRecord values(UUID value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountInstanceidRecord
     */
    public AccountInstanceidRecord() {
        super(AccountInstanceid.ACCOUNT_INSTANCEID);
    }

    /**
     * Create a detached, initialised AccountInstanceidRecord
     */
    public AccountInstanceidRecord(UUID accountid, String instanceid) {
        super(AccountInstanceid.ACCOUNT_INSTANCEID);

        setAccountid(accountid);
        setInstanceid(instanceid);
    }
}
