/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.tables.AccountCity;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountCityRecord extends UpdatableRecordImpl<AccountCityRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account_city.accountid</code>.
     */
    public void setAccountid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account_city.accountid</code>.
     */
    public UUID getAccountid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.account_city.cityid</code>.
     */
    public void setCityid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account_city.cityid</code>.
     */
    public UUID getCityid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AccountCity.ACCOUNT_CITY.ACCOUNTID;
    }

    @Override
    public Field<UUID> field2() {
        return AccountCity.ACCOUNT_CITY.CITYID;
    }

    @Override
    public UUID component1() {
        return getAccountid();
    }

    @Override
    public UUID component2() {
        return getCityid();
    }

    @Override
    public UUID value1() {
        return getAccountid();
    }

    @Override
    public UUID value2() {
        return getCityid();
    }

    @Override
    public AccountCityRecord value1(UUID value) {
        setAccountid(value);
        return this;
    }

    @Override
    public AccountCityRecord value2(UUID value) {
        setCityid(value);
        return this;
    }

    @Override
    public AccountCityRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountCityRecord
     */
    public AccountCityRecord() {
        super(AccountCity.ACCOUNT_CITY);
    }

    /**
     * Create a detached, initialised AccountCityRecord
     */
    public AccountCityRecord(UUID accountid, UUID cityid) {
        super(AccountCity.ACCOUNT_CITY);

        setAccountid(accountid);
        setCityid(cityid);
    }
}
