/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgencyProductRecord extends UpdatableRecordImpl<AgencyProductRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agency_product.agencyid</code>.
     */
    public void setAgencyid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agency_product.agencyid</code>.
     */
    public UUID getAgencyid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.agency_product.productid</code>.
     */
    public void setProductid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agency_product.productid</code>.
     */
    public UUID getProductid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AgencyProduct.AGENCY_PRODUCT.AGENCYID;
    }

    @Override
    public Field<UUID> field2() {
        return AgencyProduct.AGENCY_PRODUCT.PRODUCTID;
    }

    @Override
    public UUID component1() {
        return getAgencyid();
    }

    @Override
    public UUID component2() {
        return getProductid();
    }

    @Override
    public UUID value1() {
        return getAgencyid();
    }

    @Override
    public UUID value2() {
        return getProductid();
    }

    @Override
    public AgencyProductRecord value1(UUID value) {
        setAgencyid(value);
        return this;
    }

    @Override
    public AgencyProductRecord value2(UUID value) {
        setProductid(value);
        return this;
    }

    @Override
    public AgencyProductRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgencyProductRecord
     */
    public AgencyProductRecord() {
        super(AgencyProduct.AGENCY_PRODUCT);
    }

    /**
     * Create a detached, initialised AgencyProductRecord
     */
    public AgencyProductRecord(UUID agencyid, UUID productid) {
        super(AgencyProduct.AGENCY_PRODUCT);

        setAgencyid(agencyid);
        setProductid(productid);
    }
}
