/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.tables.AgencyDemise;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgencyDemiseRecord extends UpdatableRecordImpl<AgencyDemiseRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agency_demise.agencyid</code>.
     */
    public void setAgencyid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agency_demise.agencyid</code>.
     */
    public UUID getAgencyid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.agency_demise.demiseid</code>.
     */
    public void setDemiseid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agency_demise.demiseid</code>.
     */
    public UUID getDemiseid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AgencyDemise.AGENCY_DEMISE.AGENCYID;
    }

    @Override
    public Field<UUID> field2() {
        return AgencyDemise.AGENCY_DEMISE.DEMISEID;
    }

    @Override
    public UUID component1() {
        return getAgencyid();
    }

    @Override
    public UUID component2() {
        return getDemiseid();
    }

    @Override
    public UUID value1() {
        return getAgencyid();
    }

    @Override
    public UUID value2() {
        return getDemiseid();
    }

    @Override
    public AgencyDemiseRecord value1(UUID value) {
        setAgencyid(value);
        return this;
    }

    @Override
    public AgencyDemiseRecord value2(UUID value) {
        setDemiseid(value);
        return this;
    }

    @Override
    public AgencyDemiseRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgencyDemiseRecord
     */
    public AgencyDemiseRecord() {
        super(AgencyDemise.AGENCY_DEMISE);
    }

    /**
     * Create a detached, initialised AgencyDemiseRecord
     */
    public AgencyDemiseRecord(UUID agencyid, UUID demiseid) {
        super(AgencyDemise.AGENCY_DEMISE);

        setAgencyid(agencyid);
        setDemiseid(demiseid);
    }
}
