/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.tables.Appversions;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppversionsRecord extends UpdatableRecordImpl<AppversionsRecord> implements Record1<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.appversions.version</code>.
     */
    public void setVersion(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.appversions.version</code>.
     */
    public String getVersion() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Appversions.APPVERSIONS.VERSION;
    }

    @Override
    public String component1() {
        return getVersion();
    }

    @Override
    public String value1() {
        return getVersion();
    }

    @Override
    public AppversionsRecord value1(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public AppversionsRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppversionsRecord
     */
    public AppversionsRecord() {
        super(Appversions.APPVERSIONS);
    }

    /**
     * Create a detached, initialised AppversionsRecord
     */
    public AppversionsRecord(String version) {
        super(Appversions.APPVERSIONS);

        setVersion(version);
    }
}
