/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.tables.City;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityRecord extends UpdatableRecordImpl<CityRecord> implements Record4<UUID, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.city.cityid</code>.
     */
    public void setCityid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.city.cityid</code>.
     */
    public UUID getCityid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.city.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.city.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.city.lon</code>.
     */
    public void setLon(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.city.lon</code>.
     */
    public String getLon() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.city.lat</code>.
     */
    public void setLat(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.city.lat</code>.
     */
    public String getLat() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return City.CITY.CITYID;
    }

    @Override
    public Field<String> field2() {
        return City.CITY.NAME;
    }

    @Override
    public Field<String> field3() {
        return City.CITY.LON;
    }

    @Override
    public Field<String> field4() {
        return City.CITY.LAT;
    }

    @Override
    public UUID component1() {
        return getCityid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getLon();
    }

    @Override
    public String component4() {
        return getLat();
    }

    @Override
    public UUID value1() {
        return getCityid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getLon();
    }

    @Override
    public String value4() {
        return getLat();
    }

    @Override
    public CityRecord value1(UUID value) {
        setCityid(value);
        return this;
    }

    @Override
    public CityRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CityRecord value3(String value) {
        setLon(value);
        return this;
    }

    @Override
    public CityRecord value4(String value) {
        setLat(value);
        return this;
    }

    @Override
    public CityRecord values(UUID value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CityRecord
     */
    public CityRecord() {
        super(City.CITY);
    }

    /**
     * Create a detached, initialised CityRecord
     */
    public CityRecord(UUID cityid, String name, String lon, String lat) {
        super(City.CITY);

        setCityid(cityid);
        setName(name);
        setLon(lon);
        setLat(lat);
    }
}
