/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.tables.DemiseCity;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemiseCityRecord extends TableRecordImpl<DemiseCityRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.demise_city.demiseid</code>.
     */
    public void setDemiseid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.demise_city.demiseid</code>.
     */
    public UUID getDemiseid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.demise_city.cityid</code>.
     */
    public void setCityid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.demise_city.cityid</code>.
     */
    public UUID getCityid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return DemiseCity.DEMISE_CITY.DEMISEID;
    }

    @Override
    public Field<UUID> field2() {
        return DemiseCity.DEMISE_CITY.CITYID;
    }

    @Override
    public UUID component1() {
        return getDemiseid();
    }

    @Override
    public UUID component2() {
        return getCityid();
    }

    @Override
    public UUID value1() {
        return getDemiseid();
    }

    @Override
    public UUID value2() {
        return getCityid();
    }

    @Override
    public DemiseCityRecord value1(UUID value) {
        setDemiseid(value);
        return this;
    }

    @Override
    public DemiseCityRecord value2(UUID value) {
        setCityid(value);
        return this;
    }

    @Override
    public DemiseCityRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DemiseCityRecord
     */
    public DemiseCityRecord() {
        super(DemiseCity.DEMISE_CITY);
    }

    /**
     * Create a detached, initialised DemiseCityRecord
     */
    public DemiseCityRecord(UUID demiseid, UUID cityid) {
        super(DemiseCity.DEMISE_CITY);

        setDemiseid(demiseid);
        setCityid(cityid);
    }
}
