/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.tables.Demise;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemiseRecord extends UpdatableRecordImpl<DemiseRecord> implements Record19<UUID, String, String, String, LocalDate, String, LocalDateTime, String, String, String, String, String, LocalDateTime, LocalDateTime, String, Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.demise.demiseid</code>.
     */
    public void setDemiseid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.demise.demiseid</code>.
     */
    public UUID getDemiseid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.demise.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.demise.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.demise.surname</code>.
     */
    public void setSurname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.demise.surname</code>.
     */
    public String getSurname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.demise.photourl</code>.
     */
    public void setPhotourl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.demise.photourl</code>.
     */
    public String getPhotourl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.demise.date</code>.
     */
    public void setDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.demise.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.demise.obituary</code>.
     */
    public void setObituary(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.demise.obituary</code>.
     */
    public String getObituary() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.demise.wakets</code>.
     */
    public void setWakets(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.demise.wakets</code>.
     */
    public LocalDateTime getWakets() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.demise.wakeaddress</code>.
     */
    public void setWakeaddress(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.demise.wakeaddress</code>.
     */
    public String getWakeaddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.demise.phonenumber</code>.
     */
    public void setPhonenumber(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.demise.phonenumber</code>.
     */
    public String getPhonenumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.demise.phoneprefix</code>.
     */
    public void setPhoneprefix(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.demise.phoneprefix</code>.
     */
    public String getPhoneprefix() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.demise.phonehash</code>.
     */
    public void setPhonehash(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.demise.phonehash</code>.
     */
    public String getPhonehash() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.demise.phoneprefixhash</code>.
     */
    public void setPhoneprefixhash(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.demise.phoneprefixhash</code>.
     */
    public String getPhoneprefixhash() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.demise.ts</code>.
     */
    public void setTs(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.demise.ts</code>.
     */
    public LocalDateTime getTs() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.demise.funeralts</code>.
     */
    public void setFuneralts(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.demise.funeralts</code>.
     */
    public LocalDateTime getFuneralts() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.demise.funeraladdress</code>.
     */
    public void setFuneraladdress(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.demise.funeraladdress</code>.
     */
    public String getFuneraladdress() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.demise.age</code>.
     */
    public void setAge(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.demise.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.demise.cityname</code>.
     */
    public void setCityname(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.demise.cityname</code>.
     */
    public String getCityname() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.demise.wakenotes</code>.
     */
    public void setWakenotes(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.demise.wakenotes</code>.
     */
    public String getWakenotes() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.demise.funeralnotes</code>.
     */
    public void setFuneralnotes(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.demise.funeralnotes</code>.
     */
    public String getFuneralnotes() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<UUID, String, String, String, LocalDate, String, LocalDateTime, String, String, String, String, String, LocalDateTime, LocalDateTime, String, Integer, String, String, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<UUID, String, String, String, LocalDate, String, LocalDateTime, String, String, String, String, String, LocalDateTime, LocalDateTime, String, Integer, String, String, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Demise.DEMISE.DEMISEID;
    }

    @Override
    public Field<String> field2() {
        return Demise.DEMISE.NAME;
    }

    @Override
    public Field<String> field3() {
        return Demise.DEMISE.SURNAME;
    }

    @Override
    public Field<String> field4() {
        return Demise.DEMISE.PHOTOURL;
    }

    @Override
    public Field<LocalDate> field5() {
        return Demise.DEMISE.DATE;
    }

    @Override
    public Field<String> field6() {
        return Demise.DEMISE.OBITUARY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Demise.DEMISE.WAKETS;
    }

    @Override
    public Field<String> field8() {
        return Demise.DEMISE.WAKEADDRESS;
    }

    @Override
    public Field<String> field9() {
        return Demise.DEMISE.PHONENUMBER;
    }

    @Override
    public Field<String> field10() {
        return Demise.DEMISE.PHONEPREFIX;
    }

    @Override
    public Field<String> field11() {
        return Demise.DEMISE.PHONEHASH;
    }

    @Override
    public Field<String> field12() {
        return Demise.DEMISE.PHONEPREFIXHASH;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Demise.DEMISE.TS;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return Demise.DEMISE.FUNERALTS;
    }

    @Override
    public Field<String> field15() {
        return Demise.DEMISE.FUNERALADDRESS;
    }

    @Override
    public Field<Integer> field16() {
        return Demise.DEMISE.AGE;
    }

    @Override
    public Field<String> field17() {
        return Demise.DEMISE.CITYNAME;
    }

    @Override
    public Field<String> field18() {
        return Demise.DEMISE.WAKENOTES;
    }

    @Override
    public Field<String> field19() {
        return Demise.DEMISE.FUNERALNOTES;
    }

    @Override
    public UUID component1() {
        return getDemiseid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSurname();
    }

    @Override
    public String component4() {
        return getPhotourl();
    }

    @Override
    public LocalDate component5() {
        return getDate();
    }

    @Override
    public String component6() {
        return getObituary();
    }

    @Override
    public LocalDateTime component7() {
        return getWakets();
    }

    @Override
    public String component8() {
        return getWakeaddress();
    }

    @Override
    public String component9() {
        return getPhonenumber();
    }

    @Override
    public String component10() {
        return getPhoneprefix();
    }

    @Override
    public String component11() {
        return getPhonehash();
    }

    @Override
    public String component12() {
        return getPhoneprefixhash();
    }

    @Override
    public LocalDateTime component13() {
        return getTs();
    }

    @Override
    public LocalDateTime component14() {
        return getFuneralts();
    }

    @Override
    public String component15() {
        return getFuneraladdress();
    }

    @Override
    public Integer component16() {
        return getAge();
    }

    @Override
    public String component17() {
        return getCityname();
    }

    @Override
    public String component18() {
        return getWakenotes();
    }

    @Override
    public String component19() {
        return getFuneralnotes();
    }

    @Override
    public UUID value1() {
        return getDemiseid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSurname();
    }

    @Override
    public String value4() {
        return getPhotourl();
    }

    @Override
    public LocalDate value5() {
        return getDate();
    }

    @Override
    public String value6() {
        return getObituary();
    }

    @Override
    public LocalDateTime value7() {
        return getWakets();
    }

    @Override
    public String value8() {
        return getWakeaddress();
    }

    @Override
    public String value9() {
        return getPhonenumber();
    }

    @Override
    public String value10() {
        return getPhoneprefix();
    }

    @Override
    public String value11() {
        return getPhonehash();
    }

    @Override
    public String value12() {
        return getPhoneprefixhash();
    }

    @Override
    public LocalDateTime value13() {
        return getTs();
    }

    @Override
    public LocalDateTime value14() {
        return getFuneralts();
    }

    @Override
    public String value15() {
        return getFuneraladdress();
    }

    @Override
    public Integer value16() {
        return getAge();
    }

    @Override
    public String value17() {
        return getCityname();
    }

    @Override
    public String value18() {
        return getWakenotes();
    }

    @Override
    public String value19() {
        return getFuneralnotes();
    }

    @Override
    public DemiseRecord value1(UUID value) {
        setDemiseid(value);
        return this;
    }

    @Override
    public DemiseRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DemiseRecord value3(String value) {
        setSurname(value);
        return this;
    }

    @Override
    public DemiseRecord value4(String value) {
        setPhotourl(value);
        return this;
    }

    @Override
    public DemiseRecord value5(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public DemiseRecord value6(String value) {
        setObituary(value);
        return this;
    }

    @Override
    public DemiseRecord value7(LocalDateTime value) {
        setWakets(value);
        return this;
    }

    @Override
    public DemiseRecord value8(String value) {
        setWakeaddress(value);
        return this;
    }

    @Override
    public DemiseRecord value9(String value) {
        setPhonenumber(value);
        return this;
    }

    @Override
    public DemiseRecord value10(String value) {
        setPhoneprefix(value);
        return this;
    }

    @Override
    public DemiseRecord value11(String value) {
        setPhonehash(value);
        return this;
    }

    @Override
    public DemiseRecord value12(String value) {
        setPhoneprefixhash(value);
        return this;
    }

    @Override
    public DemiseRecord value13(LocalDateTime value) {
        setTs(value);
        return this;
    }

    @Override
    public DemiseRecord value14(LocalDateTime value) {
        setFuneralts(value);
        return this;
    }

    @Override
    public DemiseRecord value15(String value) {
        setFuneraladdress(value);
        return this;
    }

    @Override
    public DemiseRecord value16(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public DemiseRecord value17(String value) {
        setCityname(value);
        return this;
    }

    @Override
    public DemiseRecord value18(String value) {
        setWakenotes(value);
        return this;
    }

    @Override
    public DemiseRecord value19(String value) {
        setFuneralnotes(value);
        return this;
    }

    @Override
    public DemiseRecord values(UUID value1, String value2, String value3, String value4, LocalDate value5, String value6, LocalDateTime value7, String value8, String value9, String value10, String value11, String value12, LocalDateTime value13, LocalDateTime value14, String value15, Integer value16, String value17, String value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DemiseRecord
     */
    public DemiseRecord() {
        super(Demise.DEMISE);
    }

    /**
     * Create a detached, initialised DemiseRecord
     */
    public DemiseRecord(UUID demiseid, String name, String surname, String photourl, LocalDate date, String obituary, LocalDateTime wakets, String wakeaddress, String phonenumber, String phoneprefix, String phonehash, String phoneprefixhash, LocalDateTime ts, LocalDateTime funeralts, String funeraladdress, Integer age, String cityname, String wakenotes, String funeralnotes) {
        super(Demise.DEMISE);

        setDemiseid(demiseid);
        setName(name);
        setSurname(surname);
        setPhotourl(photourl);
        setDate(date);
        setObituary(obituary);
        setWakets(wakets);
        setWakeaddress(wakeaddress);
        setPhonenumber(phonenumber);
        setPhoneprefix(phoneprefix);
        setPhonehash(phonehash);
        setPhoneprefixhash(phoneprefixhash);
        setTs(ts);
        setFuneralts(funeralts);
        setFuneraladdress(funeraladdress);
        setAge(age);
        setCityname(cityname);
        setWakenotes(wakenotes);
        setFuneralnotes(funeralnotes);
    }
}
