/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.enums.Kinship;
import it.ripapp.ripapp.jooqgen.tables.DemiseRelative;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemiseRelativeRecord extends UpdatableRecordImpl<DemiseRelativeRecord> implements Record7<UUID, UUID, UUID, Kinship, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.demise_relative.relativeid</code>.
     */
    public void setRelativeid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.demise_relative.relativeid</code>.
     */
    public UUID getRelativeid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.demise_relative.demiseid</code>.
     */
    public void setDemiseid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.demise_relative.demiseid</code>.
     */
    public UUID getDemiseid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.demise_relative.accountid</code>.
     */
    public void setAccountid(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.demise_relative.accountid</code>.
     */
    public UUID getAccountid() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.demise_relative.kinship</code>.
     */
    public void setKinship(Kinship value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.demise_relative.kinship</code>.
     */
    public Kinship getKinship() {
        return (Kinship) get(3);
    }

    /**
     * Setter for <code>public.demise_relative.phone</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.demise_relative.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.demise_relative.phonehash</code>.
     */
    public void setPhonehash(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.demise_relative.phonehash</code>.
     */
    public String getPhonehash() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.demise_relative.prefix</code>.
     */
    public void setPrefix(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.demise_relative.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, UUID, Kinship, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, UUID, UUID, Kinship, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return DemiseRelative.DEMISE_RELATIVE.RELATIVEID;
    }

    @Override
    public Field<UUID> field2() {
        return DemiseRelative.DEMISE_RELATIVE.DEMISEID;
    }

    @Override
    public Field<UUID> field3() {
        return DemiseRelative.DEMISE_RELATIVE.ACCOUNTID;
    }

    @Override
    public Field<Kinship> field4() {
        return DemiseRelative.DEMISE_RELATIVE.KINSHIP;
    }

    @Override
    public Field<String> field5() {
        return DemiseRelative.DEMISE_RELATIVE.PHONE;
    }

    @Override
    public Field<String> field6() {
        return DemiseRelative.DEMISE_RELATIVE.PHONEHASH;
    }

    @Override
    public Field<String> field7() {
        return DemiseRelative.DEMISE_RELATIVE.PREFIX;
    }

    @Override
    public UUID component1() {
        return getRelativeid();
    }

    @Override
    public UUID component2() {
        return getDemiseid();
    }

    @Override
    public UUID component3() {
        return getAccountid();
    }

    @Override
    public Kinship component4() {
        return getKinship();
    }

    @Override
    public String component5() {
        return getPhone();
    }

    @Override
    public String component6() {
        return getPhonehash();
    }

    @Override
    public String component7() {
        return getPrefix();
    }

    @Override
    public UUID value1() {
        return getRelativeid();
    }

    @Override
    public UUID value2() {
        return getDemiseid();
    }

    @Override
    public UUID value3() {
        return getAccountid();
    }

    @Override
    public Kinship value4() {
        return getKinship();
    }

    @Override
    public String value5() {
        return getPhone();
    }

    @Override
    public String value6() {
        return getPhonehash();
    }

    @Override
    public String value7() {
        return getPrefix();
    }

    @Override
    public DemiseRelativeRecord value1(UUID value) {
        setRelativeid(value);
        return this;
    }

    @Override
    public DemiseRelativeRecord value2(UUID value) {
        setDemiseid(value);
        return this;
    }

    @Override
    public DemiseRelativeRecord value3(UUID value) {
        setAccountid(value);
        return this;
    }

    @Override
    public DemiseRelativeRecord value4(Kinship value) {
        setKinship(value);
        return this;
    }

    @Override
    public DemiseRelativeRecord value5(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public DemiseRelativeRecord value6(String value) {
        setPhonehash(value);
        return this;
    }

    @Override
    public DemiseRelativeRecord value7(String value) {
        setPrefix(value);
        return this;
    }

    @Override
    public DemiseRelativeRecord values(UUID value1, UUID value2, UUID value3, Kinship value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DemiseRelativeRecord
     */
    public DemiseRelativeRecord() {
        super(DemiseRelative.DEMISE_RELATIVE);
    }

    /**
     * Create a detached, initialised DemiseRelativeRecord
     */
    public DemiseRelativeRecord(UUID relativeid, UUID demiseid, UUID accountid, Kinship kinship, String phone, String phonehash, String prefix) {
        super(DemiseRelative.DEMISE_RELATIVE);

        setRelativeid(relativeid);
        setDemiseid(demiseid);
        setAccountid(accountid);
        setKinship(kinship);
        setPhone(phone);
        setPhonehash(phonehash);
        setPrefix(prefix);
    }
}
