/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemiseReadRecord extends UpdatableRecordImpl<DemiseReadRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.demise_read.accountid</code>.
     */
    public void setAccountid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.demise_read.accountid</code>.
     */
    public UUID getAccountid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.demise_read.demiseid</code>.
     */
    public void setDemiseid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.demise_read.demiseid</code>.
     */
    public UUID getDemiseid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return DemiseRead.DEMISE_READ.ACCOUNTID;
    }

    @Override
    public Field<UUID> field2() {
        return DemiseRead.DEMISE_READ.DEMISEID;
    }

    @Override
    public UUID component1() {
        return getAccountid();
    }

    @Override
    public UUID component2() {
        return getDemiseid();
    }

    @Override
    public UUID value1() {
        return getAccountid();
    }

    @Override
    public UUID value2() {
        return getDemiseid();
    }

    @Override
    public DemiseReadRecord value1(UUID value) {
        setAccountid(value);
        return this;
    }

    @Override
    public DemiseReadRecord value2(UUID value) {
        setDemiseid(value);
        return this;
    }

    @Override
    public DemiseReadRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DemiseReadRecord
     */
    public DemiseReadRecord() {
        super(DemiseRead.DEMISE_READ);
    }

    /**
     * Create a detached, initialised DemiseReadRecord
     */
    public DemiseReadRecord(UUID accountid, UUID demiseid) {
        super(DemiseRead.DEMISE_READ);

        setAccountid(accountid);
        setDemiseid(demiseid);
    }
}
