/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.tables.Phonebook;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhonebookRecord extends UpdatableRecordImpl<PhonebookRecord> implements Record6<UUID, String, String, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.phonebook.accountid</code>.
     */
    public void setAccountid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.phonebook.accountid</code>.
     */
    public UUID getAccountid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.phonebook.phonehash</code>.
     */
    public void setPhonehash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.phonebook.phonehash</code>.
     */
    public String getPhonehash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.phonebook.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.phonebook.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.phonebook.idx</code>.
     */
    public void setIdx(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.phonebook.idx</code>.
     */
    public Integer getIdx() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.phonebook.phone</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.phonebook.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.phonebook.prefix</code>.
     */
    public void setPrefix(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.phonebook.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, String, Integer, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, String, Integer, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Phonebook.PHONEBOOK.ACCOUNTID;
    }

    @Override
    public Field<String> field2() {
        return Phonebook.PHONEBOOK.PHONEHASH;
    }

    @Override
    public Field<String> field3() {
        return Phonebook.PHONEBOOK.NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Phonebook.PHONEBOOK.IDX;
    }

    @Override
    public Field<String> field5() {
        return Phonebook.PHONEBOOK.PHONE;
    }

    @Override
    public Field<String> field6() {
        return Phonebook.PHONEBOOK.PREFIX;
    }

    @Override
    public UUID component1() {
        return getAccountid();
    }

    @Override
    public String component2() {
        return getPhonehash();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer component4() {
        return getIdx();
    }

    @Override
    public String component5() {
        return getPhone();
    }

    @Override
    public String component6() {
        return getPrefix();
    }

    @Override
    public UUID value1() {
        return getAccountid();
    }

    @Override
    public String value2() {
        return getPhonehash();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Integer value4() {
        return getIdx();
    }

    @Override
    public String value5() {
        return getPhone();
    }

    @Override
    public String value6() {
        return getPrefix();
    }

    @Override
    public PhonebookRecord value1(UUID value) {
        setAccountid(value);
        return this;
    }

    @Override
    public PhonebookRecord value2(String value) {
        setPhonehash(value);
        return this;
    }

    @Override
    public PhonebookRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public PhonebookRecord value4(Integer value) {
        setIdx(value);
        return this;
    }

    @Override
    public PhonebookRecord value5(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public PhonebookRecord value6(String value) {
        setPrefix(value);
        return this;
    }

    @Override
    public PhonebookRecord values(UUID value1, String value2, String value3, Integer value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhonebookRecord
     */
    public PhonebookRecord() {
        super(Phonebook.PHONEBOOK);
    }

    /**
     * Create a detached, initialised PhonebookRecord
     */
    public PhonebookRecord(UUID accountid, String phonehash, String name, Integer idx, String phone, String prefix) {
        super(Phonebook.PHONEBOOK);

        setAccountid(accountid);
        setPhonehash(phonehash);
        setName(name);
        setIdx(idx);
        setPhone(phone);
        setPrefix(prefix);
    }
}
