/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables.records;


import it.ripapp.ripapp.jooqgen.tables.Telegram;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TelegramRecord extends UpdatableRecordImpl<TelegramRecord> implements Record11<UUID, String, String, String, String, String, String, UUID, UUID, Boolean, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.telegram.telegramid</code>.
     */
    public void setTelegramid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.telegram.telegramid</code>.
     */
    public UUID getTelegramid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.telegram.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.telegram.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.telegram.surname</code>.
     */
    public void setSurname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.telegram.surname</code>.
     */
    public String getSurname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.telegram.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.telegram.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.telegram.receiver</code>.
     */
    public void setReceiver(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.telegram.receiver</code>.
     */
    public String getReceiver() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.telegram.defunct</code>.
     */
    public void setDefunct(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.telegram.defunct</code>.
     */
    public String getDefunct() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.telegram.message</code>.
     */
    public void setMessage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.telegram.message</code>.
     */
    public String getMessage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.telegram.userid</code>.
     */
    public void setUserid(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.telegram.userid</code>.
     */
    public UUID getUserid() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.telegram.demiseid</code>.
     */
    public void setDemiseid(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.telegram.demiseid</code>.
     */
    public UUID getDemiseid() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.telegram.approvedpay</code>.
     */
    public void setApprovedpay(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.telegram.approvedpay</code>.
     */
    public Boolean getApprovedpay() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.telegram.paymentid</code>.
     */
    public void setPaymentid(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.telegram.paymentid</code>.
     */
    public String getPaymentid() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<UUID, String, String, String, String, String, String, UUID, UUID, Boolean, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<UUID, String, String, String, String, String, String, UUID, UUID, Boolean, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Telegram.TELEGRAM.TELEGRAMID;
    }

    @Override
    public Field<String> field2() {
        return Telegram.TELEGRAM.NAME;
    }

    @Override
    public Field<String> field3() {
        return Telegram.TELEGRAM.SURNAME;
    }

    @Override
    public Field<String> field4() {
        return Telegram.TELEGRAM.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Telegram.TELEGRAM.RECEIVER;
    }

    @Override
    public Field<String> field6() {
        return Telegram.TELEGRAM.DEFUNCT;
    }

    @Override
    public Field<String> field7() {
        return Telegram.TELEGRAM.MESSAGE;
    }

    @Override
    public Field<UUID> field8() {
        return Telegram.TELEGRAM.USERID;
    }

    @Override
    public Field<UUID> field9() {
        return Telegram.TELEGRAM.DEMISEID;
    }

    @Override
    public Field<Boolean> field10() {
        return Telegram.TELEGRAM.APPROVEDPAY;
    }

    @Override
    public Field<String> field11() {
        return Telegram.TELEGRAM.PAYMENTID;
    }

    @Override
    public UUID component1() {
        return getTelegramid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSurname();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getReceiver();
    }

    @Override
    public String component6() {
        return getDefunct();
    }

    @Override
    public String component7() {
        return getMessage();
    }

    @Override
    public UUID component8() {
        return getUserid();
    }

    @Override
    public UUID component9() {
        return getDemiseid();
    }

    @Override
    public Boolean component10() {
        return getApprovedpay();
    }

    @Override
    public String component11() {
        return getPaymentid();
    }

    @Override
    public UUID value1() {
        return getTelegramid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSurname();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getReceiver();
    }

    @Override
    public String value6() {
        return getDefunct();
    }

    @Override
    public String value7() {
        return getMessage();
    }

    @Override
    public UUID value8() {
        return getUserid();
    }

    @Override
    public UUID value9() {
        return getDemiseid();
    }

    @Override
    public Boolean value10() {
        return getApprovedpay();
    }

    @Override
    public String value11() {
        return getPaymentid();
    }

    @Override
    public TelegramRecord value1(UUID value) {
        setTelegramid(value);
        return this;
    }

    @Override
    public TelegramRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TelegramRecord value3(String value) {
        setSurname(value);
        return this;
    }

    @Override
    public TelegramRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public TelegramRecord value5(String value) {
        setReceiver(value);
        return this;
    }

    @Override
    public TelegramRecord value6(String value) {
        setDefunct(value);
        return this;
    }

    @Override
    public TelegramRecord value7(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public TelegramRecord value8(UUID value) {
        setUserid(value);
        return this;
    }

    @Override
    public TelegramRecord value9(UUID value) {
        setDemiseid(value);
        return this;
    }

    @Override
    public TelegramRecord value10(Boolean value) {
        setApprovedpay(value);
        return this;
    }

    @Override
    public TelegramRecord value11(String value) {
        setPaymentid(value);
        return this;
    }

    @Override
    public TelegramRecord values(UUID value1, String value2, String value3, String value4, String value5, String value6, String value7, UUID value8, UUID value9, Boolean value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TelegramRecord
     */
    public TelegramRecord() {
        super(Telegram.TELEGRAM);
    }

    /**
     * Create a detached, initialised TelegramRecord
     */
    public TelegramRecord(UUID telegramid, String name, String surname, String email, String receiver, String defunct, String message, UUID userid, UUID demiseid, Boolean approvedpay, String paymentid) {
        super(Telegram.TELEGRAM);

        setTelegramid(telegramid);
        setName(name);
        setSurname(surname);
        setEmail(email);
        setReceiver(receiver);
        setDefunct(defunct);
        setMessage(message);
        setUserid(userid);
        setDemiseid(demiseid);
        setApprovedpay(approvedpay);
        setPaymentid(paymentid);
    }
}
