/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables;


import it.ripapp.ripapp.jooqgen.Keys;
import it.ripapp.ripapp.jooqgen.Public;
import it.ripapp.ripapp.jooqgen.tables.records.AccountCityRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountCity extends TableImpl<AccountCityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.account_city</code>
     */
    public static final AccountCity ACCOUNT_CITY = new AccountCity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountCityRecord> getRecordType() {
        return AccountCityRecord.class;
    }

    /**
     * The column <code>public.account_city.accountid</code>.
     */
    public final TableField<AccountCityRecord, UUID> ACCOUNTID = createField(DSL.name("accountid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.account_city.cityid</code>.
     */
    public final TableField<AccountCityRecord, UUID> CITYID = createField(DSL.name("cityid"), SQLDataType.UUID.nullable(false), this, "");

    private AccountCity(Name alias, Table<AccountCityRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccountCity(Name alias, Table<AccountCityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.account_city</code> table reference
     */
    public AccountCity(String alias) {
        this(DSL.name(alias), ACCOUNT_CITY);
    }

    /**
     * Create an aliased <code>public.account_city</code> table reference
     */
    public AccountCity(Name alias) {
        this(alias, ACCOUNT_CITY);
    }

    /**
     * Create a <code>public.account_city</code> table reference
     */
    public AccountCity() {
        this(DSL.name("account_city"), null);
    }

    public <O extends Record> AccountCity(Table<O> child, ForeignKey<O, AccountCityRecord> key) {
        super(child, key, ACCOUNT_CITY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<AccountCityRecord> getPrimaryKey() {
        return Keys.ACCOUNT_CITY_PKEY;
    }

    @Override
    public List<UniqueKey<AccountCityRecord>> getKeys() {
        return Arrays.<UniqueKey<AccountCityRecord>>asList(Keys.ACCOUNT_CITY_PKEY);
    }

    @Override
    public List<ForeignKey<AccountCityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AccountCityRecord, ?>>asList(Keys.ACCOUNT_CITY__ACCOUNT_CITY_ACCOUNTID_FKEY, Keys.ACCOUNT_CITY__ACCOUNT_CITY_CITYID_FKEY);
    }

    private transient Account _account;
    private transient City _city;

    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.ACCOUNT_CITY__ACCOUNT_CITY_ACCOUNTID_FKEY);

        return _account;
    }

    public City city() {
        if (_city == null)
            _city = new City(this, Keys.ACCOUNT_CITY__ACCOUNT_CITY_CITYID_FKEY);

        return _city;
    }

    @Override
    public AccountCity as(String alias) {
        return new AccountCity(DSL.name(alias), this);
    }

    @Override
    public AccountCity as(Name alias) {
        return new AccountCity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountCity rename(String name) {
        return new AccountCity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountCity rename(Name name) {
        return new AccountCity(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
