/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables;


import it.ripapp.ripapp.jooqgen.Keys;
import it.ripapp.ripapp.jooqgen.Public;
import it.ripapp.ripapp.jooqgen.tables.records.AgencyDemiseRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgencyDemise extends TableImpl<AgencyDemiseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agency_demise</code>
     */
    public static final AgencyDemise AGENCY_DEMISE = new AgencyDemise();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgencyDemiseRecord> getRecordType() {
        return AgencyDemiseRecord.class;
    }

    /**
     * The column <code>public.agency_demise.agencyid</code>.
     */
    public final TableField<AgencyDemiseRecord, UUID> AGENCYID = createField(DSL.name("agencyid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agency_demise.demiseid</code>.
     */
    public final TableField<AgencyDemiseRecord, UUID> DEMISEID = createField(DSL.name("demiseid"), SQLDataType.UUID.nullable(false), this, "");

    private AgencyDemise(Name alias, Table<AgencyDemiseRecord> aliased) {
        this(alias, aliased, null);
    }

    private AgencyDemise(Name alias, Table<AgencyDemiseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.agency_demise</code> table reference
     */
    public AgencyDemise(String alias) {
        this(DSL.name(alias), AGENCY_DEMISE);
    }

    /**
     * Create an aliased <code>public.agency_demise</code> table reference
     */
    public AgencyDemise(Name alias) {
        this(alias, AGENCY_DEMISE);
    }

    /**
     * Create a <code>public.agency_demise</code> table reference
     */
    public AgencyDemise() {
        this(DSL.name("agency_demise"), null);
    }

    public <O extends Record> AgencyDemise(Table<O> child, ForeignKey<O, AgencyDemiseRecord> key) {
        super(child, key, AGENCY_DEMISE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<AgencyDemiseRecord> getPrimaryKey() {
        return Keys.AGENCY_DEMISE_PKEY;
    }

    @Override
    public List<UniqueKey<AgencyDemiseRecord>> getKeys() {
        return Arrays.<UniqueKey<AgencyDemiseRecord>>asList(Keys.AGENCY_DEMISE_PKEY);
    }

    @Override
    public List<ForeignKey<AgencyDemiseRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AgencyDemiseRecord, ?>>asList(Keys.AGENCY_DEMISE__AGENCY_DEMISE_AGENCYID_FKEY, Keys.AGENCY_DEMISE__AGENCY_DEMISE_DEMISEID_FKEY);
    }

    private transient Agency _agency;
    private transient Demise _demise;

    public Agency agency() {
        if (_agency == null)
            _agency = new Agency(this, Keys.AGENCY_DEMISE__AGENCY_DEMISE_AGENCYID_FKEY);

        return _agency;
    }

    public Demise demise() {
        if (_demise == null)
            _demise = new Demise(this, Keys.AGENCY_DEMISE__AGENCY_DEMISE_DEMISEID_FKEY);

        return _demise;
    }

    @Override
    public AgencyDemise as(String alias) {
        return new AgencyDemise(DSL.name(alias), this);
    }

    @Override
    public AgencyDemise as(Name alias) {
        return new AgencyDemise(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgencyDemise rename(String name) {
        return new AgencyDemise(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgencyDemise rename(Name name) {
        return new AgencyDemise(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
