/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables;


import it.ripapp.ripapp.jooqgen.Keys;
import it.ripapp.ripapp.jooqgen.Public;
import it.ripapp.ripapp.jooqgen.tables.records.AgencyOperatorRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgencyOperator extends TableImpl<AgencyOperatorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agency_operator</code>
     */
    public static final AgencyOperator AGENCY_OPERATOR = new AgencyOperator();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgencyOperatorRecord> getRecordType() {
        return AgencyOperatorRecord.class;
    }

    /**
     * The column <code>public.agency_operator.agencyid</code>.
     */
    public final TableField<AgencyOperatorRecord, UUID> AGENCYID = createField(DSL.name("agencyid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.agency_operator.accountid</code>.
     */
    public final TableField<AgencyOperatorRecord, UUID> ACCOUNTID = createField(DSL.name("accountid"), SQLDataType.UUID.nullable(false), this, "");

    private AgencyOperator(Name alias, Table<AgencyOperatorRecord> aliased) {
        this(alias, aliased, null);
    }

    private AgencyOperator(Name alias, Table<AgencyOperatorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.agency_operator</code> table reference
     */
    public AgencyOperator(String alias) {
        this(DSL.name(alias), AGENCY_OPERATOR);
    }

    /**
     * Create an aliased <code>public.agency_operator</code> table reference
     */
    public AgencyOperator(Name alias) {
        this(alias, AGENCY_OPERATOR);
    }

    /**
     * Create a <code>public.agency_operator</code> table reference
     */
    public AgencyOperator() {
        this(DSL.name("agency_operator"), null);
    }

    public <O extends Record> AgencyOperator(Table<O> child, ForeignKey<O, AgencyOperatorRecord> key) {
        super(child, key, AGENCY_OPERATOR);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<AgencyOperatorRecord> getPrimaryKey() {
        return Keys.AGENCY_OPERATOR_PKEY;
    }

    @Override
    public List<UniqueKey<AgencyOperatorRecord>> getKeys() {
        return Arrays.<UniqueKey<AgencyOperatorRecord>>asList(Keys.AGENCY_OPERATOR_PKEY);
    }

    @Override
    public List<ForeignKey<AgencyOperatorRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AgencyOperatorRecord, ?>>asList(Keys.AGENCY_OPERATOR__AGENCY_OPERATOR_AGENCYID_FKEY, Keys.AGENCY_OPERATOR__AGENCY_OPERATOR_ACCOUNTID_FKEY);
    }

    private transient Agency _agency;
    private transient Account _account;

    public Agency agency() {
        if (_agency == null)
            _agency = new Agency(this, Keys.AGENCY_OPERATOR__AGENCY_OPERATOR_AGENCYID_FKEY);

        return _agency;
    }

    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.AGENCY_OPERATOR__AGENCY_OPERATOR_ACCOUNTID_FKEY);

        return _account;
    }

    @Override
    public AgencyOperator as(String alias) {
        return new AgencyOperator(DSL.name(alias), this);
    }

    @Override
    public AgencyOperator as(Name alias) {
        return new AgencyOperator(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgencyOperator rename(String name) {
        return new AgencyOperator(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgencyOperator rename(Name name) {
        return new AgencyOperator(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
