/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables;


import it.ripapp.ripapp.jooqgen.Keys;
import it.ripapp.ripapp.jooqgen.Public;
import it.ripapp.ripapp.jooqgen.tables.records.CounterSetRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CounterSet extends TableImpl<CounterSetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.counter_set</code>
     */
    public static final CounterSet COUNTER_SET = new CounterSet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CounterSetRecord> getRecordType() {
        return CounterSetRecord.class;
    }

    /**
     * The column <code>public.counter_set.accountid</code>.
     */
    public final TableField<CounterSetRecord, UUID> ACCOUNTID = createField(DSL.name("accountid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.counter_set.unread</code>.
     */
    public final TableField<CounterSetRecord, Integer> UNREAD = createField(DSL.name("unread"), SQLDataType.INTEGER.nullable(false), this, "");

    private CounterSet(Name alias, Table<CounterSetRecord> aliased) {
        this(alias, aliased, null);
    }

    private CounterSet(Name alias, Table<CounterSetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.counter_set</code> table reference
     */
    public CounterSet(String alias) {
        this(DSL.name(alias), COUNTER_SET);
    }

    /**
     * Create an aliased <code>public.counter_set</code> table reference
     */
    public CounterSet(Name alias) {
        this(alias, COUNTER_SET);
    }

    /**
     * Create a <code>public.counter_set</code> table reference
     */
    public CounterSet() {
        this(DSL.name("counter_set"), null);
    }

    public <O extends Record> CounterSet(Table<O> child, ForeignKey<O, CounterSetRecord> key) {
        super(child, key, COUNTER_SET);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<CounterSetRecord> getPrimaryKey() {
        return Keys.COUNTER_SET_PKEY;
    }

    @Override
    public List<UniqueKey<CounterSetRecord>> getKeys() {
        return Arrays.<UniqueKey<CounterSetRecord>>asList(Keys.COUNTER_SET_PKEY);
    }

    @Override
    public List<ForeignKey<CounterSetRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CounterSetRecord, ?>>asList(Keys.COUNTER_SET__COUNTER_SET_ACCOUNTID_FKEY);
    }

    private transient Account _account;

    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.COUNTER_SET__COUNTER_SET_ACCOUNTID_FKEY);

        return _account;
    }

    @Override
    public List<Check<CounterSetRecord>> getChecks() {
        return Arrays.<Check<CounterSetRecord>>asList(
              Internal.createCheck(this, DSL.name("counter_set_unread_check"), "((unread >= 0))", true)
        );
    }

    @Override
    public CounterSet as(String alias) {
        return new CounterSet(DSL.name(alias), this);
    }

    @Override
    public CounterSet as(Name alias) {
        return new CounterSet(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CounterSet rename(String name) {
        return new CounterSet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CounterSet rename(Name name) {
        return new CounterSet(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
