/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables;


import it.ripapp.ripapp.jooqgen.enums.Kinship;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.UUID;


/*
* VINCOLI NON AGGIUNTI:
* unique(relativeid, accountid)
* unique(relativeid, phone)
* */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class DemiseRelative {

    @Id
    private UUID RELATIVEID;

    @OneToMany
    @Cascade(CascadeType.ALL)
    private ArrayList<Demise> demises;

    private UUID DEMISEID;
    private UUID ACCOUNTID;
    private Kinship KINSHIP;
    private String PHONE; //? verificare utilizzo di demiserelative.phone in altre classi
    private String PHONEHASH;
    private String PREFIX;
}
