/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables;


import it.ripapp.ripapp.jooqgen.Keys;
import it.ripapp.ripapp.jooqgen.Public;
import it.ripapp.ripapp.jooqgen.tables.records.DemiseReadRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemiseRead extends TableImpl<DemiseReadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.demise_read</code>
     */
    public static final DemiseRead DEMISE_READ = new DemiseRead();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DemiseReadRecord> getRecordType() {
        return DemiseReadRecord.class;
    }

    /**
     * The column <code>public.demise_read.accountid</code>.
     */
    public final TableField<DemiseReadRecord, UUID> ACCOUNTID = createField(DSL.name("accountid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.demise_read.demiseid</code>.
     */
    public final TableField<DemiseReadRecord, UUID> DEMISEID = createField(DSL.name("demiseid"), SQLDataType.UUID.nullable(false), this, "");

    private DemiseRead(Name alias, Table<DemiseReadRecord> aliased) {
        this(alias, aliased, null);
    }

    private DemiseRead(Name alias, Table<DemiseReadRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.demise_read</code> table reference
     */
    public DemiseRead(String alias) {
        this(DSL.name(alias), DEMISE_READ);
    }

    /**
     * Create an aliased <code>public.demise_read</code> table reference
     */
    public DemiseRead(Name alias) {
        this(alias, DEMISE_READ);
    }

    /**
     * Create a <code>public.demise_read</code> table reference
     */
    public DemiseRead() {
        this(DSL.name("demise_read"), null);
    }

    public <O extends Record> DemiseRead(Table<O> child, ForeignKey<O, DemiseReadRecord> key) {
        super(child, key, DEMISE_READ);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<DemiseReadRecord> getPrimaryKey() {
        return Keys.DEMISE_READ_PKEY;
    }

    @Override
    public List<UniqueKey<DemiseReadRecord>> getKeys() {
        return Arrays.<UniqueKey<DemiseReadRecord>>asList(Keys.DEMISE_READ_PKEY);
    }

    @Override
    public List<ForeignKey<DemiseReadRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DemiseReadRecord, ?>>asList(Keys.DEMISE_READ__DEMISE_READ_ACCOUNTID_FKEY, Keys.DEMISE_READ__DEMISE_READ_DEMISEID_FKEY);
    }

    private transient Account _account;
    private transient Demise _demise;

    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.DEMISE_READ__DEMISE_READ_ACCOUNTID_FKEY);

        return _account;
    }

    public Demise demise() {
        if (_demise == null)
            _demise = new Demise(this, Keys.DEMISE_READ__DEMISE_READ_DEMISEID_FKEY);

        return _demise;
    }

    @Override
    public DemiseRead as(String alias) {
        return new DemiseRead(DSL.name(alias), this);
    }

    @Override
    public DemiseRead as(Name alias) {
        return new DemiseRead(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DemiseRead rename(String name) {
        return new DemiseRead(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DemiseRead rename(Name name) {
        return new DemiseRead(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
