/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables;


import it.ripapp.ripapp.jooqgen.Keys;
import it.ripapp.ripapp.jooqgen.Public;
import it.ripapp.ripapp.jooqgen.enums.Kinship;
import it.ripapp.ripapp.jooqgen.enums.Lang;
import it.ripapp.ripapp.jooqgen.tables.records.NotificationKinshipTextRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationKinshipText extends TableImpl<NotificationKinshipTextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.notification_kinship_text</code>
     */
    public static final NotificationKinshipText NOTIFICATION_KINSHIP_TEXT = new NotificationKinshipText();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationKinshipTextRecord> getRecordType() {
        return NotificationKinshipTextRecord.class;
    }

    /**
     * The column <code>public.notification_kinship_text.kinship</code>.
     */
    public final TableField<NotificationKinshipTextRecord, Kinship> KINSHIP = createField(DSL.name("kinship"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(it.ripapp.ripapp.jooqgen.enums.Kinship.class), this, "");

    /**
     * The column <code>public.notification_kinship_text.lang</code>.
     */
    public final TableField<NotificationKinshipTextRecord, Lang> LANG = createField(DSL.name("lang"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(it.ripapp.ripapp.jooqgen.enums.Lang.class), this, "");

    /**
     * The column <code>public.notification_kinship_text.text</code>.
     */
    public final TableField<NotificationKinshipTextRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.VARCHAR.nullable(false), this, "");

    private NotificationKinshipText(Name alias, Table<NotificationKinshipTextRecord> aliased) {
        this(alias, aliased, null);
    }

    private NotificationKinshipText(Name alias, Table<NotificationKinshipTextRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.notification_kinship_text</code> table reference
     */
    public NotificationKinshipText(String alias) {
        this(DSL.name(alias), NOTIFICATION_KINSHIP_TEXT);
    }

    /**
     * Create an aliased <code>public.notification_kinship_text</code> table reference
     */
    public NotificationKinshipText(Name alias) {
        this(alias, NOTIFICATION_KINSHIP_TEXT);
    }

    /**
     * Create a <code>public.notification_kinship_text</code> table reference
     */
    public NotificationKinshipText() {
        this(DSL.name("notification_kinship_text"), null);
    }

    public <O extends Record> NotificationKinshipText(Table<O> child, ForeignKey<O, NotificationKinshipTextRecord> key) {
        super(child, key, NOTIFICATION_KINSHIP_TEXT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<NotificationKinshipTextRecord> getPrimaryKey() {
        return Keys.NOTIFICATION_KINSHIP_TEXT_PKEY;
    }

    @Override
    public List<UniqueKey<NotificationKinshipTextRecord>> getKeys() {
        return Arrays.<UniqueKey<NotificationKinshipTextRecord>>asList(Keys.NOTIFICATION_KINSHIP_TEXT_PKEY);
    }

    @Override
    public NotificationKinshipText as(String alias) {
        return new NotificationKinshipText(DSL.name(alias), this);
    }

    @Override
    public NotificationKinshipText as(Name alias) {
        return new NotificationKinshipText(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationKinshipText rename(String name) {
        return new NotificationKinshipText(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationKinshipText rename(Name name) {
        return new NotificationKinshipText(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Kinship, Lang, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
