/*
 * This file is generated by jOOQ.
 */
package it.ripapp.ripapp.jooqgen.tables;


import it.ripapp.ripapp.jooqgen.Keys;
import it.ripapp.ripapp.jooqgen.Public;
import it.ripapp.ripapp.jooqgen.enums.Lang;
import it.ripapp.ripapp.jooqgen.tables.records.NotificationTextRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationText extends TableImpl<NotificationTextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.notification_text</code>
     */
    public static final NotificationText NOTIFICATION_TEXT = new NotificationText();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationTextRecord> getRecordType() {
        return NotificationTextRecord.class;
    }

    /**
     * The column <code>public.notification_text.lang</code>.
     */
    public final TableField<NotificationTextRecord, Lang> LANG = createField(DSL.name("lang"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(it.ripapp.ripapp.jooqgen.enums.Lang.class), this, "");

    /**
     * The column <code>public.notification_text.text</code>.
     */
    public final TableField<NotificationTextRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.VARCHAR.nullable(false), this, "");

    private NotificationText(Name alias, Table<NotificationTextRecord> aliased) {
        this(alias, aliased, null);
    }

    private NotificationText(Name alias, Table<NotificationTextRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.notification_text</code> table reference
     */
    public NotificationText(String alias) {
        this(DSL.name(alias), NOTIFICATION_TEXT);
    }

    /**
     * Create an aliased <code>public.notification_text</code> table reference
     */
    public NotificationText(Name alias) {
        this(alias, NOTIFICATION_TEXT);
    }

    /**
     * Create a <code>public.notification_text</code> table reference
     */
    public NotificationText() {
        this(DSL.name("notification_text"), null);
    }

    public <O extends Record> NotificationText(Table<O> child, ForeignKey<O, NotificationTextRecord> key) {
        super(child, key, NOTIFICATION_TEXT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<NotificationTextRecord> getPrimaryKey() {
        return Keys.NOTIFICATION_TEXT_PKEY;
    }

    @Override
    public List<UniqueKey<NotificationTextRecord>> getKeys() {
        return Arrays.<UniqueKey<NotificationTextRecord>>asList(Keys.NOTIFICATION_TEXT_PKEY);
    }

    @Override
    public NotificationText as(String alias) {
        return new NotificationText(DSL.name(alias), this);
    }

    @Override
    public NotificationText as(Name alias) {
        return new NotificationText(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationText rename(String name) {
        return new NotificationText(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationText rename(Name name) {
        return new NotificationText(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Lang, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
